### PR TITLE
Added handling of qupath segmap and huggingface timeouts

### PR DESCRIPTION
**Pull request by JLrumberger**
**What is the purpose of this PR?**

1. Handling qupath saved RGB segmentation maps by converting them back to single-channel label images with the following formula `label = RED * 256 * 256 + GREEN * 256 + BLUE` to decrease friction for users according to #18 .
2. Always checking local and huggingface model versions requires internet access whenever one wants to run nimbus inference. This is not a good design I think, thus I added some exception handling workflow so that you can run nimbus without internet access if a local checkpoint is available.

**How did you implement your changes**

1. Added function `handle_qupath_segmentation_map` to utils that converts RGB segmentation maps to single channel ones, this function only gets called in the Dataset class `if len(instance_mask.shape) == 3 and instance_mask.shape[-1] == 3`.
2. Added a try / except clause to the huggingface version lookup routine in the Nimbus class.

**Remaining issues**

None

### CODE REVIEW

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Looks good, did you test out the logic for local checkpoints?

**Comment by JLrumberger** [comment]
Tested it again and it threw errors. I debugged it and it should work properly now. It's also possible to write tests for this with VCRpy, I'll look into this tomorrow to see how much effort it would be.

**Comment by ngreenwald** [comment]
Got it, most important is just that you make sure it works with your own testing. If it's easy to automate, sounds good, but no problem if not.

**Comment by JLrumberger** [comment]
I found an easy way to automate it. `pytest-socket` let's me enable and disable the network connection. I also lowered the data structure for the segmentation map from uint64 (allowing for 18.4*10^19 individual cells) to uint32 (allowing for 4.3*10^9 or 4.3 billion individual cells). My guess is that WSIs won't have more than 20 million cells, even 2cm x 2cm specimen WSIs shouldn't be over say 80 millions, so uint32 should be more than enough and we save memory.

**Review by ngreenwald — APPROVED** [review]
Awesome, sounds good

**Pull request merged**
